# Generated by Django 4.0.3 on 2022-10-11 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(blank=True, max_length=255)),
                ('Content', models.TextField()),
                ('Thumbnail', models.FileField(upload_to='./thumbnail')),
                ('Type', models.CharField(blank=True, max_length=40)),
                ('Hashtag', models.CharField(blank=True, max_length=255)),
                ('Groups', models.IntegerField()),
                ('RestaurantsId', models.IntegerField(null=True)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('CommentId', models.AutoField(primary_key=True, serialize=False)),
                ('PostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts')),
            ],
        ),
    ]
