# Generated by Django 4.0.3 on 2022-10-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Hashtag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
