# Generated by Django 4.0.3 on 2022-10-11 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_posts_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='CreationTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
