# Generated by Django 4.0.3 on 2022-10-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_posts_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Thumbnail',
            field=models.ImageField(null=True, upload_to='./thumbnail'),
        ),
    ]
